import { repo, selectDownloads, formatSize } from './downloads.js';
const navigation=document.querySelector('#navigation');
const menu=document.querySelector('.menu-toggle');
navigation.classList.add('enhanced');menu.hidden=false;
const closeMenu=()=>{document.querySelector('.header').classList.remove('menu-open');menu.setAttribute('aria-expanded','false')};
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';document.querySelector('.header').classList.toggle('menu-open',open);menu.setAttribute('aria-expanded',String(open))});
navigation.addEventListener('click',event=>{if(event.target.closest('a'))closeMenu()});
document.addEventListener('keydown',event=>{if(event.key==='Escape' && menu.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus()}});
const tabs=[...document.querySelectorAll('[data-tab]')];
document.querySelector('.feature-tabs').setAttribute('role','tablist');
function activateTab(index){tabs.forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===index));tab.tabIndex=i===index?0:-1;document.querySelector(`[data-panel="${tab.dataset.tab}"]`).hidden=i!==index})}
tabs.forEach((tab,index)=>{tab.setAttribute('role','tab');tab.setAttribute('aria-controls',`panel-${tab.dataset.tab}`);const panel=document.querySelector(`[data-panel="${tab.dataset.tab}"]`);panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',tab.id);tab.addEventListener('click',()=>activateTab(index));tab.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();activateTab(next);tabs[next].focus()})});activateTab(0);
const list=document.querySelector('#download-list'),state=document.querySelector('#feed-state');let channel='stable',generation=0,controller;
const cache=new Map();
function element(tag,text,className){const node=document.createElement(tag);if(text)node.textContent=text;if(className)node.className=className;return node}
function renderDownloads(assets){list.replaceChildren();if(!assets.length)throw new Error('此渠道暂时没有可用安装包');for(const platform of ['Windows','macOS','Linux']){const matches=assets.filter(x=>x.platform===platform);if(!matches.length)continue;const row=element('div',null,'download-row'),info=element('div');info.append(element('h3',platform),element('p',platform==='macOS'?'仅 Apple Silicon · 未公证':'请核对架构与 SHA256SUMS.txt'));const links=element('div',null,'download-assets');for(const asset of matches){const link=element('a',null,'asset-link');link.href=asset.browser_download_url;link.append(element('span',`${asset.architecture} ↓`),element('small',`${asset.version} · ${formatSize(asset.size)}`));link.title=`${asset.name}\nSHA-256: ${asset.sha256}`;links.append(link)}row.append(info,links);list.append(row)}const notes=element('div',null,'release-links');for(const tag of [...new Set(assets.map(a=>a.tag))]){const a=element('a',`${tag.replace('zed-cn-','')} 发布说明 ↗`);a.href=`${repo}/releases/tag/${tag}`;notes.append(a)}list.append(notes)}
async function loadChannel(next){channel=next;const id=++generation;controller?.abort();controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);document.querySelectorAll('[data-channel]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.channel===next)));document.querySelector('#channel-description').textContent=next==='stable'?'Stable：面向日常使用的正式发布。具体功能与限制请阅读对应发布说明。':'Dev：开发渠道，可能包含尚未稳定的改动。与 Stable 共用安装和应用数据位置，切换前建议备份设置。';state.textContent='正在读取发布清单…';list.setAttribute('aria-busy','true');list.replaceChildren(element('p','正在读取已完成的发布…','download-placeholder'));try{let feed=cache.get(next);if(!feed){const response=await fetch(new URL(next==='stable'?'./updates.json':'./updates-dev.json',document.baseURI),{signal:controller.signal,cache:'no-cache'});if(!response.ok)throw new Error('发布清单暂时不可用');const text=await response.text();if(text.length>8*1024*1024)throw new Error('发布清单过大');feed=JSON.parse(text);cache.set(next,feed)}if(id!==generation)return;const assets=selectDownloads(feed,next);renderDownloads(assets);state.textContent=`${next.toUpperCase()} / 发布清单已加载`}catch(error){if(id!==generation)return;state.textContent='暂时无法读取发布清单';const message=element('p','可以在 GitHub Releases 查看实际版本与安装包。','download-placeholder');const link=element('a',' 浏览全部发布 ↗');link.href=`${repo}/releases`;message.append(link);list.replaceChildren(message)}finally{clearTimeout(timeout);if(id===generation)list.setAttribute('aria-busy','false')}}
document.querySelectorAll('[data-channel]').forEach(button=>button.addEventListener('click',()=>loadChannel(button.dataset.channel)));
loadChannel(channel);
const host=document.querySelector('#sculpture');
if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches && !navigator.connection?.saveData){import('./sculpture.js').then(({mountSculpture})=>mountSculpture(host)).catch(()=>{})}
