//! 把 `locales/*.json` 编译期转换为 `&'static str` 查找表。
//!
//! 每个 `locales/<id>.json` 是一个扁平的 `{"key": "文案"}` 映射，生成一个同样签名的
//! 查询函数；`Locale` 枚举与函数表由本文件统一生成，新增语言不需要改代码。

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=locales");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_root = Path::new(&manifest_dir)
        .parent()
        .and_then(Path::parent)
        .expect("i18n crate must live in <workspace>/crates/i18n")
        .to_path_buf();
    let locales_dir = workspace_root.join("locales");

    let mut locale_ids: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&locales_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map(|e| e == "json").unwrap_or(false) {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    locale_ids.push(stem.to_string());
                }
            }
        }
    }
    locale_ids.sort();
    if locale_ids.is_empty() {
        panic!("no locale files found in {}", locales_dir.display());
    }
    // 英文是唯一必需的回退语言
    if !locale_ids.iter().any(|id| id == "en") {
        panic!("locales/en.json is required as the fallback language");
    }
    // 默认与回退顺序：中文第一（本仓库默认语言），英文第二
    locale_ids.sort_by_key(|id| if id == "zh-Hans" { 0 } else { 1 });

    let mut code = String::new();
    code.push_str("// @generated by crates/i18n/build.rs from locales/*.json\n");
    code.push_str("// 请勿手改；编辑 locales/ 下的 JSON 后重新编译。\n\n");

    code.push_str("#[derive(Clone, Copy, PartialEq, Eq, Debug)]\n");
    code.push_str("pub enum Locale {\n");
    for id in &locale_ids {
        code.push_str(&format!("    {} ,\n", variant_name(id)));
    }
    code.push_str("}\n\n");

    code.push_str("impl Locale {\n");
    code.push_str("    /// 所有已编译进来的语言，顺序即默认回退顺序。\n");
    code.push_str("    pub const ALL: &'static [Locale] = &[\n");
    for id in &locale_ids {
        code.push_str(&format!("        Locale::{},\n", variant_name(id)));
    }
    code.push_str("    ];\n\n");
    code.push_str("    pub const fn id(self) -> &'static str {\n        match self {\n");
    for id in &locale_ids {
        code.push_str(&format!(
            "            Locale::{} => \"{}\",\n",
            variant_name(id),
            id
        ));
    }
    code.push_str("        }\n    }\n\n");
    code.push_str("    pub fn from_id(id: &str) -> Option<Locale> {\n        match id {\n");
    for id in &locale_ids {
        code.push_str(&format!(
            "            \"{}\" => Some(Locale::{}),\n",
            id,
            variant_name(id)
        ));
    }
    code.push_str("            _ => None,\n        }\n    }\n\n");
    code.push_str("    /// 系统语言未命中已编译语言时的默认语言。\n");
    code.push_str("    pub const DEFAULT: Locale = Locale::ZhHans;\n\n");
    code.push_str("    const fn index(self) -> u8 {\n        match self {\n");
    for (i, id) in locale_ids.iter().enumerate() {
        code.push_str(&format!(
            "            Locale::{} => {},\n",
            variant_name(id),
            i
        ));
    }
    code.push_str("        }\n    }\n\n");
    code.push_str("    pub fn from_index(index: u8) -> Locale {\n        Locale::ALL\n            .get(index as usize)\n            .copied()\n            .unwrap_or(Locale::DEFAULT)\n    }\n\n");
    code.push_str("    /// 该语言的本地显示名，用于设置界面下拉。\n");
    code.push_str("    pub fn display_name(self) -> &'static str {\n        match self {\n");
    for id in &locale_ids {
        code.push_str(&format!(
            "            Locale::{} => {},\n",
            variant_name(id),
            rust_string_literal(native_name(id))
        ));
    }
    code.push_str("        }\n    }\n");
    code.push_str("}\n\n");

    code.push_str(
        "pub fn all_locales() -> &'static [Locale] {\n    Locale::ALL\n}\n\n\
         pub fn language_names() -> Vec<(&'static str, &'static str)> {\n    Locale::ALL\n        .iter()\n        .map(|locale| (locale.id(), locale.display_name()))\n        .collect()\n}\n\n",
    );

    for id in &locale_ids {
        let json = fs::read_to_string(locales_dir.join(format!("{id}.json")))
            .unwrap_or_else(|e| panic!("failed to read locales/{id}.json: {e}"));
        let map: serde_json::Map<String, serde_json::Value> =
            serde_json::from_str(&json).unwrap_or_else(|e| panic!("locales/{id}.json: {e}"));
        code.push_str(&format!(
            "fn {}(key: &str) -> Option<&'static str> {{\n    match key {{\n",
            fn_name(id)
        ));
        for (key, value) in &map {
            let text = value.as_str().unwrap_or_default();
            code.push_str(&format!(
                "        {} => Some({}),\n",
                rust_string_literal(key),
                rust_string_literal(text)
            ));
        }
        code.push_str("        _ => None,\n    }\n}\n\n");
    }

    code.push_str(
        "pub fn lookup(locale: Locale, key: &str) -> Option<&'static str> {\n    match locale {\n",
    );
    for id in &locale_ids {
        code.push_str(&format!(
            "        Locale::{} => {}(key),\n",
            variant_name(id),
            fn_name(id)
        ));
    }
    code.push_str("    }\n}\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("generated.rs"), code).unwrap();
}

fn native_name(id: &str) -> &str {
    // 语言的本地自称；未知语言回退到 BCP-47 ID。
    match id {
        "zh-Hans" => "简体中文",
        "en" => "English",
        _ => id,
    }
}

fn variant_name(id: &str) -> String {
    // zh-Hans -> ZhHans，en -> En，ja -> Ja
    let mut name = String::new();
    let mut upper_next = true;
    for c in id.chars() {
        if c.is_ascii_alphanumeric() {
            if upper_next {
                name.extend(c.to_uppercase());
                upper_next = false;
            } else {
                name.push(c.to_ascii_lowercase());
            }
        } else {
            upper_next = true;
        }
    }
    name
}

fn fn_name(id: &str) -> String {
    format!("lookup_{}", id.replace(['-', '.'], "_").to_lowercase())
}

fn rust_string_literal(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
